name: client
description: internshipProject

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  google_nav_bar: ^5.0.6
  flutter_launcher_icons: "^0.11.0"
  image_picker: ^0.8.6+1
  fluttertoast: ^8.1.2
  flutter_spinkit: ^5.1.0
  blurry_modal_progress_hud: ^1.0.3
  modal_progress_hud_nsn: ^0.3.0
  animated_text_kit: ^4.2.2
  intl: ^0.18.0
  url_launcher: ^6.1.9
  d_chart: ^2.2.11



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: century
      fonts:
        - asset: fonts/CenturyGothic.ttf
